obj-m += Hello.o

#KDIR = /usr/src/linux-headers-3.2.0-24-generic-pae
# uname -r and ls /usr/src
KDIR = /usr/src/linux-headers-5.0.0-36-generic

all:
	$(MAKE) -C $(KDIR) SUBDIRS=$(PWD) modules

clean:
	rm -rf *.o *.ko *.mod.* *.symvers *.order
